language: python
python:
    - '2.7'
    - 'pypy'

install:
    - pip install -r requirements.txt

script:
    true

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3

cache:
  directories:
    - $HOME/.cache/pip
